In [1]:
import numpy as np

In [2]:
arr=np.arange(1,11)

In [3]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [4]:
arr[8]

9

In [5]:
arr[1:5]

array([2, 3, 4, 5])

In [6]:
arr[::-1]

array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1])

In [7]:
arr[2:]

array([ 3,  4,  5,  6,  7,  8,  9, 10])

In [8]:
arr[0:4]=100

In [9]:
arr

array([100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [10]:
arr

array([100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [11]:
arr=np.arange(0,11)

In [12]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [13]:
slice_of_arr=arr[0:6]

In [14]:
slice_of_arr[:]=99

In [15]:
slice_of_arr

array([99, 99, 99, 99, 99, 99])

In [16]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [17]:
arr_copy=arr.copy()

In [18]:
arr_copy[0:6]=100

In [19]:
arr_copy

array([100, 100, 100, 100, 100, 100,   6,   7,   8,   9,  10])

In [20]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [21]:
#2d array below

In [22]:
arr_2d=np.array([[5,10,15],[20,25,12],[3,7,9]])

In [23]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 12],
       [ 3,  7,  9]])

In [24]:
arr_2d[1][2]

12

In [25]:
#row
arr_2d[1]

array([20, 25, 12])

In [26]:
#or use comma single bracet notation
arr_2d[1,2]

12

In [27]:
#sub_matrices|upto 2 nd row|coloumn 1 to last
arr_2d[:2,1:]


array([[10, 15],
       [25, 12]])

In [28]:
arr


array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [29]:
arr[arr<30]

array([ 6,  7,  8,  9, 10])

In [32]:
new_arr2d=np.arange(50).reshape(5,10)

In [33]:
new_arr2d

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [34]:
#grab 15,16,25,26
new_arr2d[1:3,5:7]

array([[15, 16],
       [25, 26]])