In [1]:
#numpy arrays
#one dimensional vector
#two dimensional matrices

In [2]:
import numpy as np

In [3]:
#cast python list to an array

In [4]:
my_list=[1,2,3]

In [5]:
arr=np.array(my_list)

In [6]:
arr

array([1, 2, 3])

In [7]:
my_mat=[[1,2,3],[4,5,6],[7,8,9]]

In [8]:
np.array(my_mat)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [9]:
#arange like as python range 
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
#one dimension
np.zeros(3)

array([0., 0., 0.])

In [12]:
#two dimension like tuples
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [13]:
np.ones((3,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [15]:
#linspace 0 to 5 equal 20 portion
np.linspace(0,5,20)

array([0.        , 0.26315789, 0.52631579, 0.78947368, 1.05263158,
       1.31578947, 1.57894737, 1.84210526, 2.10526316, 2.36842105,
       2.63157895, 2.89473684, 3.15789474, 3.42105263, 3.68421053,
       3.94736842, 4.21052632, 4.47368421, 4.73684211, 5.        ])

In [16]:
#identity matrix
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [17]:
#random.rand=uniform distribution from 0 to 1
np.random.rand(5)

array([0.10331108, 0.58511469, 0.76093506, 0.10081373, 0.23172591])

In [18]:
np.random.rand(5,3)

array([[0.42458859, 0.74147427, 0.50826021],
       [0.17871512, 0.37777415, 0.40965188],
       [0.76509449, 0.27086224, 0.6884866 ],
       [0.51338372, 0.68013343, 0.95773428],
       [0.25689932, 0.03202966, 0.28226805]])

In [19]:
#random.randn=standard normal distribution
np.random.randn(2)

array([0.26812273, 0.10021795])

In [20]:
#randint(low inclusive,high exclusive,size) random integer

In [21]:
np.random.randint(1,100,10)

array([31, 28, 25, 70, 71, 48, 29, 10, 88, 21])