In [1]:
my_list=[1,2,3,4]


In [2]:
import numpy as np

In [3]:
arr=np.array(my_list)

In [4]:
arr

array([1, 2, 3, 4])

In [5]:
my_mat=[[1,2,3],[4,5,6],[7,8,9]]

In [6]:
np.array(my_mat)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [7]:
np.arange(0,11)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [8]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

In [9]:
np.zeros(3)

array([0., 0., 0.])

In [10]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [11]:
np.ones(4)

array([1., 1., 1., 1.])

In [12]:
np.linspace(0,5,10)

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

In [13]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [14]:
np.random.rand(5)

array([0.87187234, 0.91054942, 0.91726136, 0.98890715, 0.03777589])

In [15]:
np.random.rand(4,3)

array([[0.51997115, 0.46003572, 0.00824569],
       [0.59241866, 0.11052008, 0.51491367],
       [0.67619597, 0.02995616, 0.47825927],
       [0.63312709, 0.64165256, 0.15399523]])

In [17]:
np.random.randn(4)#normal or gausian distribution |not uniform distribution

array([ 0.33521992, -0.53085157,  1.04995308, -0.40683068])

In [18]:
np.random.randint(1,100)

44

In [19]:
np.random.randint(1,100,5)

array([48, 43, 29, 63, 58])

In [20]:
arr1=np.arange(25)

In [21]:
arr1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [22]:
arr1.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [23]:
ranarr=np.random.randint(1,80,10)

In [24]:
ranarr


array([15, 48, 77,  5, 54, 39,  4, 32, 33, 52])

In [25]:
ranarr.max()

77

In [26]:
ranarr.min()

4

In [27]:
ranarr.argmax()#index of max value

2

In [28]:
arr1.dtype

dtype('int32')